### ISSUE TITLE
502 errors from reverse proxy

### ISSUE THREAD

**Issue by jrandall** [wtsi-hgi/treeserve#10]
When behind a reverse proxy, lstatTree often fails to properly handle a request and the proxy eventually returns a 502 http status (after timing out). The lstatTree output doesn't indicate that it has seen the request at all - it may be that the proxy and/or browser may be caching and is sending a preflight to check whether it needs to do a GET or if the cached version is still good. Perhaps fossa does not properly support HTTP/1.1?

**Comment by jrandall** [comment]
Apache's error log says things like:

```
[Thu Feb 26 10:06:28.455806 2015] [proxy_http:error] [pid 16091:tid 140181977929472] (70007)The timeout specified has expired: [client 193.62.203.125:33159] AH01102: error reading status line from remote server hgs4k.internal.sanger.ac.uk:50114, referer: https://idp.sanger.ac.uk/idp/profile/SAML2/Redirect/SSO
```

**Comment by ejames604** [comment]
switching to proxygen has fixed this
