### ISSUE TITLE
json library uses huge amounts of memory

### ISSUE THREAD

**Issue by ejames604** [wtsi-hgi/treeserve#17]
I ran the proxygen branch version of testTree with and without the line that prints out the json.

This is the valgrind output without the json line...

==6091== HEAP SUMMARY:
==6091==     in use at exit: 0 bytes in 0 blocks
==6091==   total heap usage: 107 allocs, 107 frees, 4,327 bytes allocate

and with...

==6075== HEAP SUMMARY:
==6075==     in use at exit: 0 bytes in 0 blocks
==6075==   total heap usage: 1,721 allocs, 1,721 frees, 103,331 bytes allocated

I suspect that now we have the structure pretty much finalised, more streamlined toJSON functions could be written that aren't so bloaty. It's possible that the troubles we are having with fossa may actually be due to this, not the http layer. In any case, I will be rolling in the proxygen http library as it seems to be more featureful and standards compliant.

**Comment by jrandall** [comment]
I'm not sure I understand why would we care about 100k of extra RAM for the output routines when we are using many gigs of RAM for the tree? It it the malloc/frees that you are concerned about? We've had issues with the HTTP proxy errors from the beginning - before the json package was introduced. It's possible it may be taking longer to generate now which could be making it worse, but it hasn't gotten much worse.

**Comment by ejames604** [comment]
Thats 100k for the tiny test program. The full program is much worse. Am
happy to not put it down as the main cause but this may be something to
look at after proxygen is in place and we have a go at the tree building
short circuiting map idea

**Comment by jrandall** [comment]
The three servers running are taking:
scratch111: 62.9g
scratch113: 21.0g
scratch114: 5.5g

This did not appear to increase after the first request (well, scratch113 went up to 21.1g but the other two appeared to stay the same). 

I did tests with `valgrind` on a debug build both with and without the toJSON call for 10, 100, 1000, and 10000 lines of input (also checking peak usage with `valgrind --tool=massif`): 

<table>
<tr><th>Input Lines</th><th>Bytes allocated with toJSON</th><th>Bytes allocated without toJSON</th><th>Byte allocation difference</th><th>Peak usage with toJSON</th><th>Peak usage without toJSON</th><th>Peak usage difference</th></tr>
<tr><td>10</td><td>277.5M</td><td>269.3M</td><td>8.2M</td><td>269.1M</td><td>268.7M</td><td>0.4M</td></tr>
<tr><td>100</td><td>308.3M</td><td>273.7M</td><td>34.6M</td><td>270.8M</td><td>268.9M</td><td>1.9M</td></tr>
<tr><td>1k</td><td>381.9M</td><td>313.9M</td><td>68.0M</td><td>273.1M</td><td>269.2M</td><td>3.9M</td></tr>
<tr><td>10k</td><td>783.4M</td><td>711.7M</td><td>71.7M</td><td>273.2M</td><td>268.9M</td><td>4.3M</td></tr>
</table>

As you can see, the total bytes allocated do go up substantially as the tree grows in size, but the peak memory usage appears to stabilise. The json library is allocating (and freeing) temporary storage as it builds the output string. I would also point out that serializing the _entire_ tree to JSON is a much more expensive operation than we are ever likely to ask it to do during normal operation. 

I would not worry about this.
