### ISSUE TITLE
Groups and Users name not number (go version)

### ISSUE THREAD

**Issue by SJChacko** [wtsi-hgi/treeserve#24]
use getent group > ${groupfile}
getent passwd > ${passwdfile} 

like the C++ version to map groups and users

**Comment by jrandall** [comment]
This doesn't reference the commits that implement it

**Comment by jrandall** [comment]
I found it: https://github.com/wtsi-hgi/treeserve/blob/goDev/go/webserver.go#L629

Looks good to me, except obviously it is missing a command-line option to specify the location of the groups and users files.

**Comment by SJChacko** [comment]
Command line flags added added and mapping moved to output formatting function (commits 0ca5c6e and 9ed4a9b )
