### ISSUE TITLE
Go version, differences in nodes included

### ISSUE THREAD

**Issue by SJChacko** [wtsi-hgi/treeserve#29]
Difference between C++ and Go in which nodes are included. Depth interpreted differently. (C++ 1 = Go 2) One includes the directory as well as its children in *.*, the other doesn't. C++ also has entries in *.* which don't really exist due to rounding errors. 

Tidy code to reconcile differences.
The good news is, the numbers match well.  Comparison output example from small sample set showing slight misunderstanding about what to include.

**C++ number of nodes 5, Go  8   

Go has node /lustre/scratch118/compgen/vertann/jmg/*.*, missing in C++   
Go has node /lustre/scratch118/compgen/vertann/sf5/*.*, missing in C++   
Go has node /lustre/scratch118/compgen/*.*, missing in C++   

 Within tolerance matches : 1270 out of 1405**

**Comment by SJChacko** [comment]
It could be the C++ that's wrong in places (or possibly both) .... eg the original data file has two directories in  /lustre/scratch118/compgen/vertann, one belonging to g935, u13427 and the other to g935, u11885 and the C++ star dot star has just one directory belonging to 935 and root, which is the top level directory (itself) and neither of the subdirectories.

**Comment by jrandall** [comment]
Ok, yes, I see how that could happen. Agree that it would be good for `*.*` to include the inodes for the directories themselves (but not their contents).

**Comment by jrandall** [comment]
The way the c++ version is now is basically just that a directory's stats are included in the directory itself rather than in the parent. I.e. the entry for a directory is recorded where it is listed as `.` rather than in its parent where it is listed by name. That is defensible, but perhaps somewhat surprising.

**Comment by SJChacko** [comment]
so in 'star.star' if a node contains directories, files and links, should I include stats for the files and links but not the directories, and stats for the node itself? or itself and everything in it as well?

**Comment by jrandall** [comment]
I'm fixing the c++ version now so that it includes directories as part of their parents rather than as part of themselves.

**Comment by jrandall** [comment]
I've reverted that fix as the side-effect of it is that the root directory has no place to be represented at all.
